# Generated by Django 4.0.6 on 2022-10-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_coupan_coupan_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupan',
            name='maximum_usage',
        ),
    ]
