# Generated by Django 4.0.6 on 2022-10-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cartitem_cart'),
        ('adminside', '0003_remove_coupan_maximum_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_till', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True, max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_details')),
            ],
        ),
    ]
