# Generated by Django 4.0.6 on 2022-09-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('username', models.TextField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('confirm_password', models.TextField()),
                ('status', models.BooleanField(blank=True, default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=50)),
                ('category_dis', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.CharField(max_length=20)),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_dis', models.TextField()),
                ('Product_price', models.IntegerField()),
                ('ram', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=20)),
                ('image1', models.ImageField(blank=True, upload_to='uploads')),
                ('image2', models.ImageField(blank=True, upload_to='uploads')),
                ('image3', models.ImageField(blank=True, upload_to='uploads')),
                ('image4', models.ImageField(blank=True, upload_to='uploads')),
                ('stoke_status', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_details')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_data')),
            ],
        ),
    ]
