# Generated by Django 4.0.6 on 2022-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='discount_price',
            field=models.IntegerField(default='001'),
        ),
    ]
