# Generated by Django 4.0.6 on 2022-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_data_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='discount_percentage',
            field=models.IntegerField(default='0'),
        ),
    ]
