# Generated by Django 4.0.6 on 2022-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_data_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='stoke_status',
            field=models.CharField(default='100', max_length=50, null=True),
        ),
    ]
