# Generated by Django 4.0.6 on 2022-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
